var tabList = [ {
  name: "白羊座",
  en: "Aries",
  date: "3.21-4.19",
  attr: "火象",
  imgUrl: 'https://tpdoc.cn/uploads/dream/xingzuo/baiyang.png',
  imgWidth: '150rpx',
  imgHeight: (225/240*150) + 'rpx',
}, {
  name: "金牛座",
  en: "Taurus",
  date: "4.20-5.20",
  attr: "土象",
  imgUrl: 'https://tpdoc.cn/uploads/dream/xingzuo/jinniu.png',
  imgWidth: '90rpx',
  imgHeight: (265/180*90) + 'rpx',
}, {
  name: "双子座",
  en: "Gemini",
  date: "5.21-6.21",
  attr: "风象",
  imgUrl: 'https://tpdoc.cn/uploads/dream/xingzuo/shuangzi.png',
  imgWidth: '150rpx',
  imgHeight: (240/296*150) + 'rpx',
}, {
  name: "巨蟹座",
  en: "Cancer",
  date: "6.22-7.22",
  attr: "水象",
  imgUrl: 'https://tpdoc.cn/uploads/dream/xingzuo/juxie.png',
  imgWidth: '150rpx',
  imgHeight: (261/230*150) + 'rpx',

}, {
  name: "狮子座",
  en: "Leo",
  date: "7.23-8.22",
  attr: "火象",
  imgUrl: 'https://tpdoc.cn/uploads/dream/xingzuo/shizi.png',
  imgWidth: '120rpx',
  imgHeight: (270/184*120) + 'rpx',
}, {
  name: "处女座",
  en: "Virgo",
  date: "8.23-9.22",
  attr: "土象",
  imgUrl: 'https://tpdoc.cn/uploads/dream/xingzuo/chunv.png',
  imgWidth: '150rpx',
  imgHeight: (226/180*150) + 'rpx',
}, {
  name: "天秤座",
  en: "Libra",
  date: "9.23-10.23",
  attr: "风象",
  imgUrl: 'https://tpdoc.cn/uploads/dream/xingzuo/tiancheng.png',
  imgWidth: '140rpx',
  imgHeight: (225/167*140) + 'rpx',
}, {
  name: "天蝎座",
  en: "Scorpio",
  date: "10.24-11.22 ",
  attr: "水象",
  imgUrl: 'https://tpdoc.cn/uploads/dream/xingzuo/tianxie.png',
  imgWidth: '110rpx',
  imgHeight: (261/155*110) + 'rpx',
}, {
  name: "射手座",
  en: "Sagittarius",
  date: "11.23-12.21",
  attr: "火象",
  imgUrl: 'https://tpdoc.cn/uploads/dream/xingzuo/sheshou.png',
  imgWidth: '110rpx',
  imgHeight: (256/153*110) + 'rpx',
}, {
  name: "摩羯座",
  en: "Capricorn",
  date: "12.22-1.19",
  attr: "土象",
  imgUrl: 'https://tpdoc.cn/uploads/dream/xingzuo/mojie.png',
  imgWidth: '150rpx',
  imgHeight: (247/226*150) + 'rpx',
}, {
  name: "水瓶座",
  en: "Aquarius",
  date: "1.20-2.18",
  attr: "风象",
  imgUrl: 'https://tpdoc.cn/uploads/dream/xingzuo/shuiping.png',
  imgWidth: '170rpx',
  imgHeight: (229/220*170) + 'rpx',
}, {
  name: "双鱼座",
  en: "Pisces",
  date: "2.19-3.20",
  attr: "水象",
  imgUrl: 'https://tpdoc.cn/uploads/dream/xingzuo/shuangyu.png',
  imgWidth: '150rpx',
  imgHeight: (259/194*150) + 'rpx',
} ];

module.exports = {
  tabList: tabList
};